services:
  jenkins:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: jenkins_custom:v3
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "9090:8080"
      - "50000:50000"

    env_file:
      - .env

    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - TZ=Asia/Seoul

      - SONAR_TOKEN_VALUE=${SONAR_TOKEN_VALUE}
      - DOCKERHUB_NAME=${DOCKERHUB_NAME}
      - DOCKERHUB_PASSWORD=${DOCKERHUB_PASSWORD}
      - GITHUB_TOKEN_VALUE=${GITHUB_TOKEN_VALUE}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}


    volumes:
      - jenkins_home:/var/jenkins_home

      - ../casc:/var/jenkins_home/casc:ro
      - ../job-dsl:/var/jenkins_home/job-dsl:ro

      - /var/run/docker.sock:/var/run/docker.sock

    user: "root"

volumes:
  jenkins_home:  
