services:
  jenkins:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: jenkins_custom:v3
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "9090:8080"
      - "50000:50000"

    env_file:
      - .env

    environment:
      # "CASC_JENKINS_CONFIG"로 적용을 해줘야지 jenkins에서 인식하고 적용
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - TZ=Asia/Seoul

      - SONAR_TOKEN_VALUE=${SONAR_TOKEN_VALUE}
      - DOCKERHUB_NAME=${DOCKERHUB_NAME}
      - DOCKERHUB_PASSWORD=${DOCKERHUB_PASSWORD}
      - GITHUB_TOKEN_VALUE=${GITHUB_TOKEN_VALUE}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}


    volumes:
      - jenkins_home:/var/jenkins_home

      # ../casc 폴더의 yaml들이 /var/jenkins_home/casc 에서 읽히고,
      # CASC_JENKINS_CONFIG 환경변수로 Jenkins가 자동 적용
      - ../casc:/var/jenkins_home/casc:ro

      # seed.groovy, dsl/*.groovy 등을 Jenkins가 읽어 Job/Folder/View를 자동 생성
      - ../job-dsl:/var/jenkins_home/job-dsl:ro

      # Jenkins 파이프라인에서 docker build, docker run 등을 실행 가능
      - /var/run/docker.sock:/var/run/docker.sock

    user: "root"

volumes:
  jenkins_home:  
