services:
  jenkins:
    build:
      context: ..
      dockerfile: docker/dockerifle
    image: jenkins_docker:v2
    container_name: jenkins_prod
    restart: unless-stopped

    ports:
      - "9090:8080"
      - "50000:50000"

    environment:
      - CASE_JENKINS_CONFIG=/var/jenkins_home/casc
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

    volumes:
      - jenkins_home:/var/jenkins_home

      - ../casc:/var/jenkins_home/casc:ro
      - ../job-dsl:/var/jenkins_home/job-dsl:ro

      - /var/run/docker.sock:/var/run/docker.sock

    user: "root"

volumes:
  jenkins_home:  
